package nlp.scala.euler

import nlp.scala.util.Stopwatch

object P2 extends App {
  /**
   * Even Fibonacci numbers
   * Problem 2
   * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
   *
   * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
   *
   * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
   */

  def fib(a: Int = 1, b: Int = 2): Stream[Int] = a #:: fib(b, a + b)

  def solution1 = fib().takeWhile(_ < 4000000).filter(_ % 2 == 0).sum

  def solution2 = {
    fib2.takeWhile(_ < 4000000).filter(_ % 2 == 0).sum
  }

  val sw = new Stopwatch
  sw.start("solution1")
  println(solution1)
  sw.stop

  sw.start("solution2")
  val fib2: Stream[Int] = 1 #:: fib2.scanLeft(2)(_ + _)
  println(solution2)
  sw.stop
}